########## Helm chart Config ############

name: thanos-receive-controller
namespace: c
replicaCount: 1
image:
  repository: quay.io/observatorium/thanos-receive-controller
  pullPolicy: IfNotPresent

labels:
  part-of: thanos
  app: thanos-receive-controller
  controller.receive.thanos.io: thanos-receive-controller
  controller.receive.thanos.io/hashring: default
  tenant: default-tenant

configMap:
  enabled: true
  name: thanos-receive-generated
  generatedName: thanos-receive
  fileName: hashrings.json
  labels:
    part-of: thanos
    app: thanos-receive-controller
    controller.receive.thanos.io: thanos-receive-controller
    controller.receive.thanos.io/hashring: default
  data:
    hashrings.json: |-
      [
        {
          "hashring": "default",
          "tenants": []
        }
      ]


args:
  - --configmap-name=thanos-receive-generated
  - --configmap-generated-name=thanos-receive
  - --file-name=hashrings.json
  - --allow-only-ready-replicas
  - --allow-dynamic-scaling
  - --namespace=t