########## Helm chart Config ############

name: thanos-receive-controller
namespace: th-controller
replicaCount: 1
image:
  repository: quay.io/observatorium/thanos-receive-controller
  pullPolicy: IfNotPresent

labels:
  part-of: thanos
  app: thanos-receive-controller
  controller.receive.thanos.io: thanos-receive-controller
  controller.receive.thanos.io/hashring: default
  tenant: default-tenant

configMap:
  enabled: false
  # name: thanos-receive
  # generatedName: thanos-receive-generated
  # fileName: hashrings.json
  # labels:
  #   part-of: thanos
  #   app: thanos-receive-controller
  #   controller.receive.thanos.io: thanos-receive-controller
  #   controller.receive.thanos.io/hashring: default
  # data:
  #   hashrings.json: |-
  #     [{
  #           "hashring": "0",
  #           "tenants": ["foo", "bar"]
  #       },
  #       {
  #           "hashring": "1",
  #           "tenants": ["baz"]
  #       }]


args:
  - --configmap-name=thanos-receive
  - --configmap-generated-name=thanos-receive-generated
  - --file-name=hashrings.json
  - --allow-only-ready-replicas
  - --allow-dynamic-scaling
  - --namespace=th-controller