apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "configmap-secret-cloner.fullname" . }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - --configmap-name={{ .Values.args.configmapName }}
                - --secret-name={{ .Values.args.secretName }}
                - --target-namespace={{ .Values.args.targetNamespace }}
                - --namespaces={{ .Values.args.namespaces }}
                - --resource-type={{ .Values.args.resourceType }}
              resources:
                limits:
                  cpu: {{ .Values.resources.limits.cpu }}
                  memory: {{ .Values.resources.limits.memory }}
                requests:
                  cpu: {{ .Values.resources.requests.cpu }}
                  memory: {{ .Values.resources.requests.memory }}
          restartPolicy: OnFailure
