apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "configmap-secret-cloner.fullname" . }}
  labels:
    app: {{ include "configmap-secret-cloner.name" . }}
    chart: {{ include "configmap-secret-cloner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "configmap-secret-cloner.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "configmap-secret-cloner.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --configmap-name={{ .Values.args.configmapName }}
            - --secret-name={{ .Values.args.secretName }}
            - --target-namespace={{ .Values.args.targetNamespace }}
            - --namespaces={{ .Values.args.namespaces }}
            - --resource-type={{ .Values.args.resourceType }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
