apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloner
  namespace: th-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      serviceAccountName: configmap-cloner-sa
      containers:
      - name: main-container
        image: configmap_cloner:latest
        imagePullPolicy: IfNotPresent

#      - name: configmap-cloner-sidecar
#        image: configmap_cloner:latest
#        imagePullPolicy: IfNotPresent
#        command: ["/bin/sh", "-c"]
#        args: ["/scripts/configmap_cloner.sh"]
        
        volumeMounts:
        - name: configmap-cloner-script
          mountPath: /scripts/configmap_cloner.sh
          subPath: configmap_cloner.sh
      
      volumes:
      - name: configmap-cloner-script
        configMap:
          name: configmap-cloner-script