apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-cloner-rolebinding
  namespace: th-controller
subjects:
- kind: ServiceAccount
  name: configmap-cloner-sa
  namespace: th-controller
roleRef:
  kind: Role
  name: configmap-cloner-role
  apiGroup: rbac.authorization.k8s.io
