apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: thanos-receive-controller
    app.kubernetes.io/name: thanos-receive-controller
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
