apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: thanos-receive-controller
    app.kubernetes.io/name: thanos-receive-controller
  namespace: {{ .Values.namespace }}